"""empty message

Revision ID: 5732f21d7315
Revises: b51b624514d1
Create Date: 2024-03-12 22:01:30.673479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5732f21d7315'
down_revision = 'b51b624514d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryPassWithKey', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encryPassWithKey')

    # ### end Alembic commands ###
