"""empty message

Revision ID: 8d090963b540
Revises: ccde6ddba969
Create Date: 2024-03-12 22:05:13.572558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d090963b540'
down_revision = 'ccde6ddba969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryPassWithKey', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encryPassWithKey')

    # ### end Alembic commands ###
