"""empty message

Revision ID: ccde6ddba969
Revises: 9727e9ebae47
Create Date: 2024-03-12 22:03:06.681629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccde6ddba969'
down_revision = '9727e9ebae47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encryPassWithKey', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('encryPassWithKey')

    # ### end Alembic commands ###
